name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    # Job name
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
